[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#1b48c4"

# Background color for the main content area.
backgroundColor = "#222222"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#4c4e6d"

# Color used for almost all text.
textColor = "#FFF8F0"

[server]
fileWatcherType = "none"
headerless = true

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = false
