name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "smithed/**"
      - "requirements.lock"
      - "requirements-dev.lock"

  push:
    branches: [main]
    paths:
      - "smithed/**"
      - "pyproject.toml"
      - "requirements.lock"
      - "requirements-dev.lock"
      - ".github/workflows/main.yml"

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      # ---------------------------------------------
      #  -----          gather repo            -----
      # ---------------------------------------------
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ---------------------------------------------
      #  -----    setup and install python     -----
      # ---------------------------------------------
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
          cache-prefix: "python-rye"

      #----------------------------------------------
      #  -----     install & configure rye     -----
      #----------------------------------------------

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.lock') }}-${{ hashFiles('requirements-dev.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: rye sync

      #----------------------------------------------
      #  -----      pass linting & tests      -----
      #----------------------------------------------

      - name: Run linting and style checking
        run: rye run check

      - name: Run unit tests
        run: rye run test -v

      # ---------------------------------------------
      # -----          Release Package          -----
      # ---------------------------------------------
      - name: Release
        if: |
          github.repository == 'Smithed-MC/smithed-python'
          && github.event_name == 'push'
          && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          rye run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
